### ISSUE TITLE
Remove the color

### ISSUE THREAD

**Issue by Upasana23-hub** [Upasana23-hub/E-COMMERCE#133]
Hi @girianimesh ,
In this wishlist button, the color at the outside of this heart shape also gray. Please change this into white. Only the heart shape should be gray.
ref:
![Screenshot 2024-04-27 080915](https://github.com/Upasana23-hub/E-COMMERCE/assets/127583083/18b343d6-b136-4c21-aea7-02da5614a6d4)
Thanks .

**Comment by girianimesh** [comment]
It's showing which page ?

**Comment by girianimesh** [comment]
It's showing in which page?
