### ISSUE TITLE
Correct this design

### ISSUE THREAD

**Issue by Upasana23-hub** [Upasana23-hub/E-COMMERCE#158]
Hi @girianimesh ,
In the home page , correct the design given below.
ref: 
![Screenshot (97)](https://github.com/Upasana23-hub/E-COMMERCE/assets/127583083/6311adeb-dbdd-42b2-853f-8f712e5b5003)
Thank You.

**Comment by girianimesh** [comment]
Hi, @Upasana23-hub 
I have not encountered this problem.
REF:-
![image](https://github.com/Upasana23-hub/E-COMMERCE/assets/144048983/02f7e500-5dea-4e29-95f3-ed6749c65ff2)
