### ISSUE TITLE
Baby product in the women section

### ISSUE THREAD

**Issue by Upasana23-hub** [Upasana23-hub/E-COMMERCE#159]
Hi @AnkitDhar ,
A baby product is coming in the women section. Please correct it.
ref: 
![Screenshot (96)](https://github.com/Upasana23-hub/E-COMMERCE/assets/127583083/20e78cea-36f3-4a53-bad5-7932fb11abbb)
Thank You.

**Comment by AnkitDhar** [comment]
HI @Upasana23-hub ;
According to me this is a database problem . To remove the pampers card I have to do changes in Data.js file . 
Here I have attached a photo :-
![image](https://github.com/Upasana23-hub/E-COMMERCE/assets/155653461/59f40a63-e394-443c-820c-7c11a3b8d241)

This the id no of this card . Here 'name: "women skirt ladies skirt" ' is written wrong at line no 1551.

Thank You
