### ISSUE TITLE
Zip code and contact number

### ISSUE THREAD

**Issue by Upasana23-hub** [Upasana23-hub/E-COMMERCE#160]
Hi @girianimesh ,
Contact number can't be a negative number and the zip code can't be in letters. Please correct this for sign up page.
ref: 
![Screenshot (99)](https://github.com/Upasana23-hub/E-COMMERCE/assets/127583083/b5e66b93-0c04-4632-b52b-81ef51838fde)
Thank You.

**Comment by girianimesh** [comment]
Hi, @Upasana23-hub 
I have solved this issue. Please check above PR & close this .
https://github.com/Upasana23-hub/E-COMMERCE/pull/161
Thank You.
