### ISSUE TITLE
Sign Up Phone number

### ISSUE THREAD

**Issue by Upasana23-hub** [Upasana23-hub/E-COMMERCE#166]
Hi @girianimesh ,
Phone number must contain 10 numbers. Please correct this issue for Sign Up page .
ref: 
![Screenshot (100)](https://github.com/Upasana23-hub/E-COMMERCE/assets/127583083/baf8dc57-6f08-4f39-b33c-26950fb28a7d)
Thank You.

**Comment by Upasana23-hub** [comment]
Hi @girianimesh ,
Correct this issue for ZIP Code also . Thank You.

**Comment by girianimesh** [comment]
Hi @Upasana23-hub 
I have solved this issue , so please check & close this issue.
Thank You.
