### ISSUE TITLE
Remove size word

### ISSUE THREAD

**Issue by Upasana23-hub** [Upasana23-hub/E-COMMERCE#75]
Hi @girianimesh ,
When the size part is not applicable for a product , then remove the "Size" word from that card.
ref: 
![Screenshot (11)](https://github.com/Upasana23-hub/E-COMMERCE/assets/127583083/fecae945-df88-45eb-9add-05920e00b813)
Thank You.

**Comment by girianimesh** [comment]
Hi, @Upasana23-hub 
I have solved this issue .
REF:-
https://github.com/Upasana23-hub/E-COMMERCE/pull/156
please check & merge above PR. And close this issue.
